export const CHANGE_BOOK_STATUS = 'HOME_PAGE::CHANGE_BOOK_STATUS';

export const CHANGE_BOOK_FILTER = 'HOME_PAGE::CHANGE_BOOK_FILTER';

export const RESET_BOOK_FILTER = 'HOME_PAGE::RESET_BOOK_FILTER';
